GET http://localhost:8000/v1/animals/

###
POST http://localhost:8000/v1/animals/
Content-Type: application/json

{
  "id": 1,
  "name": "Nero",
  "age": 3,
  "breed": "European Cat",
  "passport": true,
  "chip": true
}

###
PUT http://localhost:8000/v1/animals/2
Content-Type: application/json

{
  "id": 2,
  "name": "Alexander Flemming",
  "age": 9,
  "breed": "Chihuahua",
  "passport": true,
  "chip": true
}

###
DELETE http://localhost:8000/v1/animals/1
Content-Type: application/json
