services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"  # Changed from 3000:3000 to match Vite's default port
    networks:
      - app-network
    depends_on:
      - back
    volumes:
      - ./front:/app
      - front_node_modules:/app/node_modules
    user: node

  back:
    build:
      context: ./back
    networks:
      - app-network
    depends_on:
      - postgres
    environment:
      - DB_NAME=${DB_NAME:-petsync}
      - DB_USER=${DB_USER:-postgres}  # Make sure this matches POSTGRES_USER
      - DB_PASSWORD=${DB_PASSWORD:-postgres}  # Make sure this matches POSTGRES_PASSWORD
      - DB_HOST=postgres
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app

  postgres:
    image: postgres:16.3-bookworm
    networks:
      - app-network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-petsync}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]  # Make sure to specify the postgres user
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    networks:
      - app-network
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
  front_node_modules:

networks:
  app-network:
    driver: bridge