# Generated by Django 5.1.3 on 2024-11-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('weight', models.IntegerField(default=None)),
                ('age', models.IntegerField(default=None)),
                ('identifyer', models.CharField(unique=True)),
                ('has_passport', models.BooleanField(default=False)),
                ('has_chip', models.BooleanField(default=False)),
                ('is_vaccined', models.BooleanField(default=False)),
                ('has_allgeries', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('AD', 'Adopted'), ('HO', 'Hosted'), ('SHE', 'Sheltered')], default='Sheltered')),
                ('shelter_name', models.CharField(max_length=50)),
            ],
        ),
    ]
