openapi: 3.0.0
info:
  title: Sample API
  description: API documentation for your Django project
  version: "1.0.0"
servers:
  - url: http://localhost:8000
paths:
  /api/sample:
    get:
      summary: Sample GET endpoint
      description: Returns a list of samples
      responses:
        '200':
          description: A list of samples
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string