openapi: 3.0.0
info:
  title: API V1
  description: This is a sample API documentation using OpenAPI 3.0.
  version: 1.0.0

tags:
  - name: Animals
    description: Operations related to animal resources
paths:
  v1/animals:
    get:
      summary: Get a list of animals
      description: Retrieve a list of all animals in the database.
      responses:
        '200':
          description: A list of animals
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    age:
                      type: integer
                    species:
                      type: string
    post:
      summary: Create a new animal
      description: Add a new animal to the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: integer
                species:
                  type: string
      responses:
        '201':
          description: The animal was created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  age:
                    type: integer
                  species:
                    type: string
        '400':
          description: Malformed animal request
          content:
            application/json:
              schema:
                type: object

  v1/animals/:id:
    get:
      summary: Get an animal
      description: Retrieve a matching animal with the given id from the database.
      responses:
        '200':
          description: A list of animals
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    age:
                      type: integer
                    species:
                      type: string
        '404':
          description: Animal not found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    delete:
      summary: Get an animal
      description: Retrieve a matching animal with the given id from the database.
      responses:
        '200':
          description: A list of animals
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    age:
                      type: integer
                    species:
                      type: string
        '404':
          description: Animal not found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    put:
      summary: Update an animal
      description: Updates a matching animal with the given information.
      responses:
        '200':
          description: A list of animals
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    age:
                      type: integer
                    species:
                      type: string
        '404':
          description: Animal not found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
