FROM node:18.16-buster-slim

# Set working directory
WORKDIR /app

# Run as root for permissions
USER root

# Set node_modules to be owned by node user
RUN mkdir -p /app/node_modules && \
    chown -R node:node /app

# Switch to node user
USER node

# Expose port
EXPOSE 3000

# Start command
CMD ["npm", "run", "dev"]