name: pipeline
on:
  push:
    branches:
      - "main"
permissions:
  packages: write
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # For frontend tests
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install frontend dependencies
        working-directory: ./front
        run: npm install
      - name: Run frontend tests
        working-directory: ./front
        run: npm test
      # For backend tests
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend dependencies
        working-directory: ./back
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run backend tests
        working-directory: ./back
        run: pytest

  build-and-push-images:
    runs-on: ubuntu-latest
    needs:
      - run-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Build and push frontend
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./front
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/front:latest
            ghcr.io/${{ github.repository }}/front:${{ github.sha }}
      # Build and push backend
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./back
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/back:latest
            ghcr.io/${{ github.repository }}/back:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-images
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Create env file
      run: |
        echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile
    - name: Docker Stack Deploy
      uses: cssnr/stack-deploy-action@v1
      with:
        name: refupet
        file: docker-compose.yml
        host: refupet.org
        user: root
        port: 7342
        ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
        env_file: ./envfile
