name: deploy-pipeline
on:
  push:
    branches:
      - "main"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install frontend dependencies
        working-directory: ./front
        run: npm install
      - name: Run frontend tests
        working-directory: ./front
        run: npm test
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend dependencies
        working-directory: ./back
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run backend tests
        working-directory: ./back
        run: pytest

  build-images:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set IMAGE_NAME
        run: |
          echo "IMAGE_NAME=ghcr.io/${{ github.repository }}" >> $GITHUB_ENV
      - name: Build frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}/front:latest
            ${{ env.IMAGE_NAME }}/front:${{ github.sha }}
      - name: Build backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./back
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}/back:latest
            ${{ env.IMAGE_NAME }}/back:${{ github.sha }}
