name: main-pipeline
on:
  push:
    branches:
      - "main"

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set IMAGE_NAME
        run: |
          echo "IMAGE_NAME=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/petsync-web" >> $GITHUB_ENV # Set Docker Hub image name
      - name: Build frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}/front:latest
            ${{ env.IMAGE_NAME }}/front:${{ github.sha }}
      - name: Build backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./back
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}/back:latest
            ${{ env.IMAGE_NAME }}/back:${{ github.sha }}
